#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

PYTHON_BIN="${PYTHON_BIN:-$SCRIPT_DIR/.venv-whisper/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
    printf 'Missing Python environment: %s\n' "$PYTHON_BIN" >&2
    printf 'Set PYTHON_BIN or create example/.venv-whisper first.\n' >&2
    exit 1
fi

export PATH="/usr/local/bin:/usr/bin:/bin:${PATH:-}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export RESPONSE_BACKEND="${RESPONSE_BACKEND:-codex}"
export STT_BACKEND="${STT_BACKEND:-local}"
export WAKE_ENGINE="${WAKE_ENGINE:-vosk}"
export WAKE_STT_BACKEND="${WAKE_STT_BACKEND:-local}"
export WAKE_VOSK_PHRASES="${WAKE_VOSK_PHRASES:-hello robot,hey robot}"
export WHISPER_MODEL="${WHISPER_MODEL:-base}"
export WHISPER_ALLOWED_LANGUAGES="${WHISPER_ALLOWED_LANGUAGES:-en,zh}"
export WHISPER_BEAM_SIZE="${WHISPER_BEAM_SIZE:-2}"
export WHISPER_CPU_THREADS="${WHISPER_CPU_THREADS:-4}"
export WHISPER_NUM_WORKERS="${WHISPER_NUM_WORKERS:-1}"
export WHISPER_SHARED_ENCODER_LANGUAGE_DETECTION="${WHISPER_SHARED_ENCODER_LANGUAGE_DETECTION:-1}"
export VOICE_START_RMS="${VOICE_START_RMS:-420}"
export END_SILENCE_SECONDS="${END_SILENCE_SECONDS:-0.55}"
export MAX_RECORD_SECONDS="${MAX_RECORD_SECONDS:-18}"
export VOICE_PREROLL_SECONDS="${VOICE_PREROLL_SECONDS:-0.45}"
export VOICE_NOISE_FLOOR_RISE_ALPHA="${VOICE_NOISE_FLOOR_RISE_ALPHA:-0.015}"
export CHAT_MEMORY_ENABLED="${CHAT_MEMORY_ENABLED:-1}"
export CHAT_MEMORY_MAX_ITEMS="${CHAT_MEMORY_MAX_ITEMS:-24}"
export CHAT_MEMORY_RELEVANT_MAX_ITEMS="${CHAT_MEMORY_RELEVANT_MAX_ITEMS:-6}"
export BARGE_IN_ENABLED="${BARGE_IN_ENABLED:-1}"
export BARGE_IN_FOLLOWUP_ENABLED="${BARGE_IN_FOLLOWUP_ENABLED:-1}"
export BARGE_IN_FOLLOWUP_START_TIMEOUT_SECONDS="${BARGE_IN_FOLLOWUP_START_TIMEOUT_SECONDS:-5}"
export BARGE_IN_FOLLOWUP_TOTAL_TIMEOUT_SECONDS="${BARGE_IN_FOLLOWUP_TOTAL_TIMEOUT_SECONDS:-45}"
export BARGE_IN_INTERRUPT_POLL_SECONDS="${BARGE_IN_INTERRUPT_POLL_SECONDS:-0.05}"
export TTS_SOFT_INTERRUPT_TIMEOUT_SECONDS="${TTS_SOFT_INTERRUPT_TIMEOUT_SECONDS:-0.35}"
export TTS_HARD_INTERRUPT_TIMEOUT_SECONDS="${TTS_HARD_INTERRUPT_TIMEOUT_SECONDS:-0.2}"
export LCD_SCREEN="${LCD_SCREEN:-2inch4}"
export TTS_PLAYBACK_DEVICE="${TTS_PLAYBACK_DEVICE:-plughw:CARD=sndrpihifiberry,DEV=0}"
export CODEX_MODEL="${CODEX_MODEL:-gpt-5.3-codex-spark}"

exec "$PYTHON_BIN" "$SCRIPT_DIR/19v2.local_voice_chatbot_interrupt_followup.py" "$@"
